# NipponRisk Analytics
"""Export the cached aligned-returns panel into a TS module for the Cloudflare Worker.

The Cloudflare Worker bundles its data as a TypeScript/JavaScript module (there is
no Python/pandas runtime on Workers), so this script snapshots
``backend/data/returns.parquet`` into ``worker/data/returns.ts`` which is imported
by the risk engine. Run it whenever you refresh the parquet cache:

    ./backend/.venv/bin/python scripts/export_worker_data.py

The output is committed to git so Cloudflare CI (wrangler build) needs no Python.
"""

from __future__ import annotations

import json
from pathlib import Path

import pandas as pd

BACKEND_PANEL = Path(__file__).resolve().parent.parent / "backend" / "data" / "returns.parquet"
OUTPUT = Path(__file__).resolve().parent.parent / "worker" / "data" / "returns.ts"
HEADER = "// Auto-generated by scripts/export_worker_data.py - do not edit by hand."


def fmt_float(v: float) -> str:
    s = json.dumps(v, allow_nan=False)
    return s


def main() -> None:
    if not BACKEND_PANEL.exists():
        raise SystemExit(f"Panel not found: {BACKEND_PANEL}")

    df = pd.read_parquet(BACKEND_PANEL)
    df.index = pd.DatetimeIndex(df.index)
    if df.index.tz is not None:
        df.index = df.index.tz_localize(None)
    df.index = df.index.normalize()

    columns = [str(c) for c in df.columns]
    dates = [d.strftime("%Y-%m-%d") for d in df.index]
    rows = df.to_numpy(dtype=float).tolist()

    lines: list[str] = [
        HEADER,
        f"// Source: backend/data/returns.parquet ({len(dates)} rows, {len(columns)} cols).",
        "// Aligned daily simple returns (decimals); index dates are tz-naive ISO dates.",
        "",
        f"export const COLUMNS: string[] = {json.dumps(columns)};",
        "",
        f"export const DATES: string[] = {json.dumps(dates)};",
        "",
        "export const RETURNS: number[][] = [",
    ]
    lines.extend(f"  [{', '.join(fmt_float(v) for v in row)}]," for row in rows)
    lines.append("];")
    lines.append("")

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUTPUT} ({len(dates)} rows x {len(columns)} cols)")


if __name__ == "__main__":
    main()